version: '3.8'

services:

  # Inicializa banco SQLite e cria usuário admin
  airflow-init:
    image: apache/airflow:2.9.1-python3.11-slim
    container_name: airflow-init
    entrypoint: /bin/bash -c
    command:
      - |
        echo "Inicializando Airflow..."
        airflow db migrate

        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin123 \
          || echo "Usuário já existe"

        echo "Airflow inicializado!"

    environment:
      # Executor mais leve para EC2 1gb de ram
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      # Banco de metadados do Airflow
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
       # Desabilita DAGs de exemplo
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      # Limita execução simultânea para reduzir consumo de memória
      AIRFLOW__CORE__PARALLELISM: 1
      AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 1
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 1

      AIRFLOW__SCHEDULER__PARSING_PROCESSES: 1

      AIRFLOW__WEBSERVER__SECRET_KEY: clash-royale-secret

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-2}

    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

    networks:
      - clash-network

  #__________________________________________________________________________________

  # Interface web do Airflow
  airflow-webserver:
    image: apache/airflow:2.9.1-python3.11-slim
    container_name: airflow-webserver

    command: webserver

    depends_on:
      airflow-init:
        condition: completed_successfully

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags

      AIRFLOW__CORE__PARALLELISM: 1
      AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 1
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 1

      AIRFLOW__WEBSERVER__SECRET_KEY: clash-royale-secret
      AIRFLOW__WEBSERVER__WORKERS: 1
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'False'

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-2}

    ports:
      - "8080:8080"

    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    mem_limit: 350m
    cpus: 0.40

    restart: unless-stopped

    networks:
      - clash-network

  #__________________________________________________________________________________

  # Responsável por executar e agendar DAGs
  airflow-scheduler:
    image: apache/airflow:2.9.1-python3.11-slim
    container_name: airflow-scheduler

    command: scheduler

    depends_on:
      airflow-init:
        condition: completed_successfully

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags

      AIRFLOW__CORE__PARALLELISM: 1
      AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 1
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 1

      AIRFLOW__SCHEDULER__PARSING_PROCESSES: 1
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 60
      AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT: 'False'

      AIRFLOW__WEBSERVER__SECRET_KEY: clash-royale-secret

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-2}

    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

    mem_limit: 350m
    cpus: 0.40

    restart: unless-stopped

    networks:
      - clash-network

  #__________________________________________________________________________________

  # App Dashboard pra visualização dos dados
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit

    container_name: clash-streamlit

    ports:
      - "8501:8501"

    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-2}

      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_HEADLESS: 'true'

      STREAMLIT_LOGGER_LEVEL: warning
      STREAMLIT_SERVER_FILE_WATCHER_TYPE: none

    volumes:
      - ./streamlit_app.py:/app/streamlit_app.py
      - ./athena_runner.py:/app/athena_runner.py
      - ./athena_queries:/app/athena_queries
      - ./logs:/app/logs

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    mem_limit: 200m
    cpus: 0.20

    restart: unless-stopped

    networks:
      - clash-network

volumes:
  airflow_data:

networks:
  clash-network:
    driver: bridge